# -----------------------------------------
# Functions and function processors
# -----------------------------------------

# Processors

<processor>             := <fct_coll> | <fct_cp> | <cumulative> ;
<fct_coll>              := APPLY <function> <p_collator> | APPLY ( <function> ) <p_collator> ;
<fct_cp>                := CONSTANT <constant> ;
<cumulative>            := COMBINE <processor> WITH <fct_name> ;

# Functions

<function>              := <fct_and> | <fct_or> | <fct_not> | <fct_eq> || <constant> ; 
<fct_and>               := <constant> ∧ <constant> | <constant> ∧ ( <function> ) | ( <function> ) ∧ <constant> | ( <function> ) ∧ ( <function> ) ;
<fct_or>                := <constant> ∨ <constant> | <constant> ∨ ( <function> ) | ( <function> ) ∨ <constant> | ( <function> ) ∨ ( <function> ) ;
<fct_not>               := ¬ <constant> | ¬ ( <function> ) ;
<fct_eq>                := <constant> = <constant> | <constant> = ( <function> ) | ( <function> ) = <constant> | ( <function> ) = ( <function> ) ;
<constant>              := <number> | <boolean> ;

# Function names; only functions from T x T -> T need to have a name

<fct_name>              := <fctn_and> | <fctn_or> ;
<fctn_and>              := CONJUNCTION ;
<fctn_or>               := DISJUNCTION ;

# Constants

<boolean>           := true | false ;