# -----------------------------------------
# Grammar for BeepBeep 3; edit at your own risk!
#
# This is an EML (Event Manipulation Language) for data structures.
#
# This grammar works in tandem with the EPL (Event Processing
# Language) grammar.
# -----------------------------------------

<eml_expr>               := <gp_heatmap> | <gp_scatterplot> | <gp_caller>;
<gp_heatmap>             := THE HEATMAP OF ( <processor> ) ;
<gp_scatterplot>         := THE SCATTERPLOT OF ( <processor> ) ;
<gp_caller>              := GNUPLOT ON ( <processor> ) ;
