# -----------------------------------------
# Grammar for BeepBeep 3; edit at your own risk!
#
# This is an EML (Event Manipulation Language) for data structures.
#
# This grammar works in tandem with the EPL (Event Processing
# Language) grammar.
# -----------------------------------------

<eml_expr>               := <sig_peak> | <sig_plateau> | <sig_thresh> ;
<sig_peak>               := THE PEAK OF ( <processor> ) ;
<sig_plateau>            := THE PLATEAU OF ( <processor> ) ;
<sig_thresh>             := ( <processor> ) THRESHOLD <number> ;
