# -----------------------------------------
# I/O processors
# -----------------------------------------

<processor>              := <p_stream> | <p_url> | <p_caller> ;
<p_stream>               := FILE <stream_string> ;
<p_url>                  := URL <stream_string> ;
<p_caller>               := CALL <stream_string> ON <processor> ;
<stream_string>          := ^".*?";