# -----------------------------------------
# Grammar for BeepBeep 3; edit at your own risk!
#
# This is an EML (Event Manipulation Language) for Linear
# Temporal Logic (LTL).
# This grammar works in tandem with the EPL (Event Processing
# Language) grammar.
# -----------------------------------------

<eml_expr>               := <ltl_operator> ;

<ltl_operator>           := <globally> | <eventually> | <next> | <until> 
                            | <ltl_not> | <ltl_and> | <ltl_or> | <eml_boolean> ;
<ltl_not>                := NOT ( <processor> ) ;
<ltl_and>                := ( <processor> ) AND ( <processor> ) ;
<ltl_or>                 := ( <processor> ) OR ( <processor> ) ;
<globally>               := G ( <processor> ) ;
<eventually>             := F ( <processor> ) ;
<next>                   := X ( <processor> ) ;
<until>                  := ( <processor> ) U ( <processor> ) ;