# -----------------------------------------
# Grammar for BeepBeep 3; edit at your own risk!
#
# This is an EML (Event Manipulation Language) where events are
# simple numbers.
# This grammar works in tandem with the EPL (Event Processing
# Language) grammar.
# -----------------------------------------

# Primitive types

<eml_number>             := ^\d+;

<eml_expr>               := <eml_number> ;

# Functions on numbers

<c_function>             := <fct_addition> | <fct_subtraction> | <fct_division>
                            | <fct_multiplication> ;
<fct_addition>           := ADDITION ;
<fct_subtraction>        := SUBTRACTION ;
<fct_division>           := DIVISION ;
<fct_multiplication>     := MULTIPLICATION ;