# -----------------------------------------
# Grammar for BeepBeep 3; edit at your own risk!
#
# This is the bootstrap part of the language.
# Working with BeepBeep 3 also requires the inclusion of at least
# one grammar for the EML (Event Manipulation Language).
# -----------------------------------------

# Top production rule

<S> := <processor> | <processor_def> ;

# Definition of a processor

<processor>          := <userdef_proc> | <eml_expr> | <p_combiner> | <p_placeholder> ; 
<p_combiner>         := COMBINE ( <processor> ) WITH <c_combine> ;

# Definition of a new grammatical object

<processor_def>      := WHEN <symbol_def_list> : <proc_pattern> IS THE <symbol_name> <string_def>
                        | <proc_pattern> IS THE <symbol_name> <string_def> ;
<symbol_def_list>    := <symbol_def> , <symbol_def_list> | <symbol_def> ;
<symbol_def>         := <symbol_var> IS A <symbol_name> ;
<proc_pattern>       := ^.*?(?=IS);
<symbol_var>         := ^@[a-zA-Z][\w_]*;	
<symbol_name>        := ^[a-zA-Z][\w_]*;
<string_def>         := ^.*;

# User-defined processors. Rules get dynamically added here

<userdef_proc>       := gnarfnfar ;